//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tiera.Properties {
    using System;

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tiera.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to wts.ItemName.
        /// </summary>
        public static string AppDisplayName {
            get {
                return ResourceManager.GetString("AppDisplayName", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to ShellGoBackButton.
        /// </summary>
        public static string ShellGoBackButton {
            get {
                return ResourceManager.GetString("ShellGoBackButton", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to ShellHamburgerButtonName.
        /// </summary>
        public static string ShellHamburgerButtonName {
            get {
                return ResourceManager.GetString("ShellHamburgerButtonName", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string DashboardPageTitle {
            get {
                return ResourceManager.GetString("DashboardPageTitle", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string ShellDashboardPage {
            get {
                return ResourceManager.GetString("ShellDashboardPage", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        public static string OrdersPageTitle {
            get {
                return ResourceManager.GetString("OrdersPageTitle", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        public static string ShellOrdersPage {
            get {
                return ResourceManager.GetString("ShellOrdersPage", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Sample Orders.
        /// </summary>
        public static string ProductsListDescription {
            get {
                return ResourceManager.GetString("ProductsListDescription", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string ProductsPageTitle {
            get {
                return ResourceManager.GetString("ProductsPageTitle", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string ShellProductsPage {
            get {
                return ResourceManager.GetString("ShellProductsPage", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Sample Orders.
        /// </summary>
        public static string ServicesListDescription {
            get {
                return ResourceManager.GetString("ServicesListDescription", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string ServicesPageTitle {
            get {
                return ResourceManager.GetString("ServicesPageTitle", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string ShellServicesPage {
            get {
                return ResourceManager.GetString("ShellServicesPage", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Sample Orders.
        /// </summary>
        public static string VetsListDescription {
            get {
                return ResourceManager.GetString("VetsListDescription", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Vets.
        /// </summary>
        public static string VetsPageTitle {
            get {
                return ResourceManager.GetString("VetsPageTitle", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Vets.
        /// </summary>
        public static string ShellVetsPage {
            get {
                return ResourceManager.GetString("ShellVetsPage", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Sample Orders.
        /// </summary>
        public static string CustomersListDescription {
            get {
                return ResourceManager.GetString("CustomersListDescription", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Customers.
        /// </summary>
        public static string CustomersPageTitle {
            get {
                return ResourceManager.GetString("CustomersPageTitle", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Customers.
        /// </summary>
        public static string ShellCustomersPage {
            get {
                return ResourceManager.GetString("ShellCustomersPage", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Sample Orders.
        /// </summary>
        public static string EmployeesListDescription {
            get {
                return ResourceManager.GetString("EmployeesListDescription", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Employees.
        /// </summary>
        public static string EmployeesPageTitle {
            get {
                return ResourceManager.GetString("EmployeesPageTitle", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Employees.
        /// </summary>
        public static string ShellEmployeesPage {
            get {
                return ResourceManager.GetString("ShellEmployeesPage", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string ReportsPageTitle {
            get {
                return ResourceManager.GetString("ReportsPageTitle", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string ShellReportsPage {
            get {
                return ResourceManager.GetString("ShellReportsPage", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to HelpPageBackButtonTooltip
        /// </summary>
        public static string HelpPageBackButtonTooltip {
            get {
                return ResourceManager.GetString("HelpPageBackButtonTooltip", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to HelpPageForwardButtonTooltip
        /// </summary>
        public static string HelpPageForwardButtonTooltip {
            get {
                return ResourceManager.GetString("HelpPageForwardButtonTooltip", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to HelpPageLoadingText
        /// </summary>
        public static string HelpPageLoadingText {
            get {
                return ResourceManager.GetString("HelpPageLoadingText", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to HelpPageFaildedMessage
        /// </summary>
        public static string HelpPageFaildedMessage {
            get {
                return ResourceManager.GetString("HelpPageFaildedMessage", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to HelpPageRefreshButtonTooltip
        /// </summary>
        public static string HelpPageRefreshButtonTooltip {
            get {
                return ResourceManager.GetString("HelpPageRefreshButtonTooltip", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to HelpPageOpenInBrowserButtonTooltip
        /// </summary>
        public static string HelpPageOpenInBrowserButtonTooltip {
            get {
                return ResourceManager.GetString("HelpPageOpenInBrowserButtonTooltip", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string ShellHelpPage {
            get {
                return ResourceManager.GetString("ShellHelpPage", resourceCulture);
            }
        }
    
        /// <summary>
            ///   Looks up a localized string similar to Settings page placeholder text.  Your app description goes here..
            /// </summary>
            public static string SettingsPageAboutText {
                get {
                    return ResourceManager.GetString("SettingsPageAboutText", resourceCulture);
                }
            }
    
            /// <summary>
            ///   Looks up a localized string similar to About this application.
            /// </summary>
            public static string SettingsPageAboutTitle {
                get {
                    return ResourceManager.GetString("SettingsPageAboutTitle", resourceCulture);
                }
            }
    
            /// <summary>
            ///   Looks up a localized string similar to Choose Theme.
            /// </summary>
            public static string SettingsPageChooseThemeText {
                get {
                    return ResourceManager.GetString("SettingsPageChooseThemeText", resourceCulture);
                }
            }
    
            /// <summary>
            ///   Looks up a localized string similar to Personalization.
            /// </summary>
            public static string SettingsPagePersonalizationTitle {
                get {
                    return ResourceManager.GetString("SettingsPagePersonalizationTitle", resourceCulture);
                }
            }
    
            /// <summary>
            ///   Looks up a localized string similar to Privacy Statement.
            /// </summary>
            public static string SettingsPagePrivacyStatementText {
                get {
                    return ResourceManager.GetString("SettingsPagePrivacyStatementText", resourceCulture);
                }
            }
    
            /// <summary>
            ///   Looks up a localized string similar to Dark.
            /// </summary>
            public static string SettingsPageRadioButtonDarkTheme {
                get {
                    return ResourceManager.GetString("SettingsPageRadioButtonDarkTheme", resourceCulture);
                }
            }
    
            /// <summary>
            ///   Looks up a localized string similar to Light.
            /// </summary>
            public static string SettingsPageRadioButtonLightTheme {
                get {
                    return ResourceManager.GetString("SettingsPageRadioButtonLightTheme", resourceCulture);
                }
            }
    
            /// <summary>
            ///   Looks up a localized string similar to Default.
            /// </summary>
            public static string SettingsPageRadioButtonWindowsDefaultTheme {
                get {
                    return ResourceManager.GetString("SettingsPageRadioButtonWindowsDefaultTheme", resourceCulture);
                }
            }
    
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string ShellSettingsPage {
            get {
                return ResourceManager.GetString("ShellSettingsPage", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to DialogAuthenticationTitle.
        /// </summary>
        public static string DialogAuthenticationTitle {
            get {
                return ResourceManager.GetString("DialogAuthenticationTitle", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to DialogNoNetworkAvailableContent.
        /// </summary>
        public static string DialogNoNetworkAvailableContent {
            get {
                return ResourceManager.GetString("DialogNoNetworkAvailableContent", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to DialogStatusUnknownErrorContent.
        /// </summary>
        public static string DialogStatusUnknownErrorContent {
            get {
                return ResourceManager.GetString("DialogStatusUnknownErrorContent", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to SettingsPageLogInButtonText.
        /// </summary>
        public static string SettingsPageLogInButtonText {
            get {
                return ResourceManager.GetString("SettingsPageLogInButtonText", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to SettingsPageNoUserLoggedInText.
        /// </summary>
        public static string SettingsPageNoUserLoggedInText {
            get {
                return ResourceManager.GetString("SettingsPageNoUserLoggedInText", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to SettingsPageUserTitle.
        /// </summary>
        public static string SettingsPageUserTitle {
            get {
                return ResourceManager.GetString("SettingsPageUserTitle", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to SettingsPageLogOutButtonText.
        /// </summary>
        public static string SettingsPageLogOutButtonText {
            get {
                return ResourceManager.GetString("SettingsPageLogOutButtonText", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Shell_LogIn.
        /// </summary>
        public static string Shell_LogIn {
            get {
                return ResourceManager.GetString("Shell_LogIn", resourceCulture);
            }
        }
    }
}
